# Generated by Django 6.0.4 on 2026-04-30 07:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesto',
            fields=[
                ('mesto_id', models.AutoField(primary_key=True, serialize=False)),
                ('nazev', models.CharField(max_length=100)),
                ('symbol', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Město',
                'verbose_name_plural': 'Města',
                'db_table': 'mesto',
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('stat_id', models.AutoField(primary_key=True, serialize=False)),
                ('nazev', models.CharField(max_length=4, unique=True)),
                ('hymna', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Stát',
                'verbose_name_plural': 'Státy',
                'db_table': 'stat',
            },
        ),
        migrations.CreateModel(
            name='Zavod',
            fields=[
                ('zavod_id', models.AutoField(primary_key=True, serialize=False)),
                ('nazev', models.CharField(max_length=100)),
                ('datum', models.DateField(blank=True, null=True)),
                ('cas_zahajeni', models.TimeField(blank=True, null=True)),
                ('misto', models.CharField(max_length=20)),
                ('bazen', models.CharField(choices=[('50', '50 metrů'), ('25', '25 metrů')], max_length=2)),
            ],
            options={
                'verbose_name': 'Závod',
                'verbose_name_plural': 'Závody',
                'db_table': 'zavod',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('disciplina_id', models.AutoField(primary_key=True, serialize=False)),
                ('nazev', models.CharField(max_length=100)),
                ('delka', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('styl', models.CharField(choices=[('volný způsob', 'Volný způsob'), ('prsa', 'Prsa'), ('motýl', 'Motýl'), ('znak', 'Znak'), ('polohový závod', 'Polohový závod')], max_length=20)),
                ('pohlavi', models.CharField(choices=[('M', 'Muž'), ('Z', 'Žena')], max_length=1)),
            ],
            options={
                'verbose_name': 'Disciplína',
                'verbose_name_plural': 'Disciplíny',
                'db_table': 'disciplina',
                'unique_together': {('styl', 'pohlavi', 'delka')},
            },
        ),
        migrations.CreateModel(
            name='Klub',
            fields=[
                ('klub_id', models.AutoField(primary_key=True, serialize=False)),
                ('nazev', models.CharField(max_length=100)),
                ('datum_zalozeni', models.DateField(blank=True, null=True)),
                ('mesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zavody.mesto')),
            ],
            options={
                'verbose_name': 'Klub',
                'verbose_name_plural': 'Kluby',
                'db_table': 'klub',
            },
        ),
        migrations.CreateModel(
            name='Plavec',
            fields=[
                ('plavec_id', models.AutoField(primary_key=True, serialize=False)),
                ('jmeno', models.CharField(max_length=100)),
                ('prijmeni', models.CharField(max_length=100)),
                ('rocnik', models.IntegerField()),
                ('vaha', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('vyska', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pohlavi', models.CharField(choices=[('M', 'Muž'), ('Z', 'Žena')], max_length=1)),
                ('foto', models.CharField(blank=True, max_length=255, null=True)),
                ('klub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zavody.klub')),
                ('stat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zavody.stat')),
            ],
            options={
                'verbose_name': 'Plavec',
                'verbose_name_plural': 'Plavci',
                'db_table': 'plavec',
            },
        ),
        migrations.AddField(
            model_name='mesto',
            name='stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zavody.stat'),
        ),
        migrations.CreateModel(
            name='Trener',
            fields=[
                ('trener_id', models.AutoField(primary_key=True, serialize=False)),
                ('jmeno', models.CharField(max_length=100)),
                ('prijmeni', models.CharField(max_length=100)),
                ('pohlavi', models.CharField(blank=True, choices=[('M', 'Muž'), ('Z', 'Žena')], max_length=1, null=True)),
                ('foto', models.CharField(blank=True, max_length=255, null=True)),
                ('klub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zavody.klub')),
                ('plavci', models.ManyToManyField(blank=True, related_name='treneri', to='zavody.plavec')),
                ('stat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zavody.stat')),
            ],
            options={
                'verbose_name': 'Trenér',
                'verbose_name_plural': 'Trenéři',
                'db_table': 'trener',
            },
        ),
        migrations.CreateModel(
            name='Vysledek',
            fields=[
                ('vysledek_id', models.AutoField(primary_key=True, serialize=False)),
                ('umisteni', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('body', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zavody.disciplina')),
                ('plavec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zavody.plavec')),
                ('zavod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zavody.zavod')),
            ],
            options={
                'verbose_name': 'Výsledek',
                'verbose_name_plural': 'Výsledky',
                'db_table': 'vysledek',
            },
        ),
        migrations.CreateModel(
            name='DisciplinyZavodu',
            fields=[
                ('discipliny_zavodu_id', models.AutoField(primary_key=True, serialize=False)),
                ('zacatek', models.TimeField()),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zavody.disciplina')),
                ('zavod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zavody.zavod')),
            ],
            options={
                'verbose_name': 'Disciplína závodu',
                'verbose_name_plural': 'Disciplíny závodu',
                'db_table': 'discipliny_zavodu',
                'unique_together': {('disciplina', 'zavod')},
            },
        ),
    ]
